echo off
set LOCALHOST=%COMPUTERNAME%
set KILL_CMD="C:\PROGRA~1\ANSYSI~1\v195\fluent/ntbin/win64/winkill.exe"

"C:\PROGRA~1\ANSYSI~1\v195\fluent\ntbin\win64\tell.exe" DESKTOP-1ABIJOM 61964 CLEANUP_EXITING
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 15412) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 11404) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 17260) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 2576) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 20016) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 2464)
del "C:\Users\TAKESTANCC\Desktop\3D\cleanup-fluent-DESKTOP-1ABIJOM-20016.bat"
