echo off
set LOCALHOST=%COMPUTERNAME%
set KILL_CMD="C:\PROGRA~1\ANSYSI~1\v195\fluent/ntbin/win64/winkill.exe"

"C:\PROGRA~1\ANSYSI~1\v195\fluent\ntbin\win64\tell.exe" DESKTOP-1ABIJOM 55687 CLEANUP_EXITING
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 10676) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 16088) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 6412) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 17656) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 1412) 
if /i "%LOCALHOST%"=="DESKTOP-1ABIJOM" (%KILL_CMD% 15132)
del "C:\Users\TAKESTANCC\Desktop\3D\cleanup-fluent-DESKTOP-1ABIJOM-1412.bat"
